### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by guoyoujin** [elevenetc/BadgeView#1]
Can you send the demo to me have a look

**Comment by elevenetc** [comment]
@guoyoujin I'll add a sample module soon.

**Comment by guoyoujin** [comment]
@elevenetc Ok, thank you very much, can be seen from the GIF animation demo you must be very cool

**Comment by cybercarrot** [comment]
could u add the sample demo soon @elevenetc, I use the lib, but I was confused by your doc

**Comment by elevenetc** [comment]
@MrCocoa Hey! Sorry for delay, added finally a [sample module](https://github.com/elevenetc/BadgeView/blob/master/sample%2Fsrc%2Fmain%2Fjava%2Fsu%2Flevenetc%2Fandroid%2Fsample%2FSampleActivity.java).
